exclude: doc/en/example/py2py3/test_py2.py
repos:
-   repo: https://github.com/ambv/black
    rev: 18.6b4
    hooks:
    -   id: black
        args: [--safe, --quiet]
        language_version: python3
-   repo: https://github.com/asottile/blacken-docs
    rev: v0.3.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==18.9b0]
        language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
        language_version: python3
    -   id: flake8
        language_version: python3
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.1.0
    hooks:
    -   id: rst-backticks
